Fixing the intro of the Markdown.
SECQUOIA/pyomo-summer-ws pull request #7
Opened 2024-08-06 00:27 UTC by AlbertLee125

I fixed the intro of the notebook by creating the hyperlink of the email. Also, I updated Zedong's Purdue Email.
I also added Hamta and her email.

And fixed the Github Hyperlink into SECQUOIA's repository.

2024-08-06 00:49 UTC, ZedongPeng commented
Hi @AlbertLee125 . The files in `_build` folder are generated automatically when you build the repository. We usually don't change them manually.
Let's first set up the GitHub Actions to build the website automatically.

2024-08-31 20:48 UTC, bernalde commented
Is this to be closed or merged?

2024-09-03 17:50 UTC, bernalde approved these changes

2024-09-03 17:58 UTC, AlbertLee125 commented
This branch has to be closed. Since Zedong and I updated the email while resolving the Homework Rendering issue, This branch can be closed.

2026-05-10 22:33 UTC, bernalde requested changes
1. blocking issues: PR #7 is not mergeable because it edits generated `_build/**` files that current `main` deleted; the repository URL update is also incomplete because `_config.yml` and `README.md` still point to the old personal fork.
2. nonblocking issues: none.
3. questions: none.
4. tests run and outcomes: `uv venv --python 3.11 .venv` succeeded on the PR branch; `uv pip install --python .venv/bin/python -r requirements.txt` failed on the PR branch because its stale `requirements.txt` contains the invalid requirement line `sphinx sphinxcontrib-mermaid`. On a current-main worktree with the PR's source notebook edits applied, `uv venv --python 3.11 .venv` and `uv pip install --python .venv/bin/python -r requirements.txt` succeeded; `.venv/bin/jupyter-book build .` with jupyter-book 2.1.5 exited 0 but printed `No file exports found` and did not perform the old-style book build; targeted JSON validation of the three changed source notebooks passed.
5. merge as-is: no. I would not merge this until the blocking issues above are addressed.

2026-05-10 22:33 UTC, bernalde commented on _build/html/_sources/notebooks/PyomoFundamentals/Fundamentals.ipynb
> +    "This notebook contains material from the Pyomo Summer Workshop 2018 by the Pyomo Developement Team and the notebook is developed by David Bernal (dbernaln@purdue.edu), Zedong Peng (peng372@purdu
Blocking: This PR is editing generated `_build/**` artifacts. Current `main` deleted these files and CI now builds the book from source, which is why GitHub reports this PR as `CONFLICTING`. Please rebase onto `main` and drop all `_build/**` changes; keep the source notebook updates and any source config/docs updates. Otherwise the merge remains blocked and stale generated output can be committed.

2026-05-10 22:33 UTC, bernalde commented on notebooks/PyomoFundamentals/Fundamentals.ipynb
> +    "This notebook contains material from the Pyomo Summer Workshop 2018 by the Pyomo Developement Team and the notebook is developed by David Bernal (dbernaln@purdue.edu), Zedong Peng (peng372@purdu
Blocking: This updates the inline notebook link, but the source for the Jupyter Book repository, issue, and Colab links still points at the old fork in `_config.yml` (`repository.url`), and `README.md` still links there as well. Users would get mixed repository destinations after a rebuild. Please update those source files to `https://github.com/SECQUOIA/pyomo-summer-ws` in the same PR so all user-facing links agree.

2026-05-10 22:40 UTC, bernalde commented
Pushed commit eae65d4 (`Address PR review feedback`).

Main changes made:
- Merged current `main` into `Email-update`, so the generated `_build/**` files removed on `main` are no longer part of the PR's net diff.
- Kept the source notebook attribution/email/repository updates in the three notebook headers.
- Updated `README.md` and `_config.yml` to point to `https://github.com/SECQUOIA/pyomo-summer-ws` so user-facing repository, issue, and Colab links agree after rebuild.

Tests run and results:
- `uv venv --python 3.11 .venv`: passed with CPython 3.11.14.
- `uv pip install --python .venv/bin/python -r requirements.txt`: passed.
- Targeted JSON validation of the three changed notebooks with `.venv/bin/python`: passed.
- `rg -n "AlbertLee125/pyomo-summer-ws|peng_zedong|123\.com| at purdue\.edu" README.md _config.yml notebooks`: no matches.
- `git diff --check origin/main...HEAD`: passed.
- `.venv/bin/jupyter-book build .`: exited 0, but with `jupyter-book` 2.1.5 it reported `No file exports found` and did not perform the older-style book build. The generated untracked `_build/` directory was removed and not committed.

Comments intentionally not addressed:
- The older top-level discussion saying the branch could be closed was not acted on by closing the PR because the current request was to address the review feedback and push the branch. The generated-file concern from that discussion is addressed by bringing in current `main` and dropping `_build/**` from the PR diff.

Remaining risks or follow-up items:
- The repository's documented CI command is affected by unpinned `jupyter-book` resolving to 2.1.5 locally; it exits 0 but does not produce the classic book build output. That appears to be a pre-existing dependency/tooling issue outside this PR's text/link changes.

2026-05-10 22:41 UTC, bernalde commented on _build/html/_sources/notebooks/PyomoFundamentals/Fundamentals.ipynb
> +    "This notebook contains material from the Pyomo Summer Workshop 2018 by the Pyomo Developement Team and the notebook is developed by David Bernal (dbernaln@purdue.edu), Zedong Peng (peng372@purdu
Addressed in https://github.com/SECQUOIA/pyomo-summer-ws/commit/eae65d404fdfb2c00e69409dfdf8eade62711568. I merged current `main` into the PR branch and kept generated `_build/**` files out of the net PR diff; `git diff --check origin/main...HEAD` and targeted notebook JSON validation passed.

2026-05-10 22:41 UTC, bernalde commented on notebooks/PyomoFundamentals/Fundamentals.ipynb
> +    "This notebook contains material from the Pyomo Summer Workshop 2018 by the Pyomo Developement Team and the notebook is developed by David Bernal (dbernaln@purdue.edu), Zedong Peng (peng372@purdu
Addressed in https://github.com/SECQUOIA/pyomo-summer-ws/commit/eae65d404fdfb2c00e69409dfdf8eade62711568. Updated `README.md` and `_config.yml` to the SECQUOIA repository URL, and confirmed no stale old-fork/email placeholders remain under `README.md`, `_config.yml`, or `notebooks/`.

2026-05-10 22:46 UTC, bernalde commented
Follow-up pushed in 389f894 to address the remaining Jupyter Book tooling risk.

Changes made:
- Pinned `jupyter-book<2` so `pip install -r requirements.txt` resolves to the classic Jupyter Book CLI that supports `jupyter-book build .`.
- Added `.venv` to `_config.yml` exclusions so local repo-root virtualenvs are not scanned as book source files.
- Moved the Google Analytics config to the current `html.analytics.google_analytics_id` key.
- Updated the intro's first-chapter link to the existing `notebooks/python/python-exercises.ipynb` file.

Validation:
- `uv venv --clear --python 3.11 .venv`: passed.
- `uv pip install --python .venv/bin/python -r requirements.txt`: passed, resolving `jupyter-book 1.0.4.post1` and `sphinx 7.4.7`.
- `.venv/bin/python` JSON validation for the three changed notebooks: passed.
- `git diff --check`: passed.
- `.venv/bin/jupyter-book build .`: passed and generated `_build/html` cleanly with no warnings.

Generated `_build/` output was removed before commit and is not part of the PR diff.

2026-05-10 22:55 UTC, bernalde reviewed
1. blocking issues: none found in this round. The prior generated `_build/**` and stale repository URL concerns are addressed, and the documented local build now succeeds.
2. nonblocking issues: existing notebook intro polish comments remain valid (`Developement`, `Github`, and double spacing in the three changed notebook attribution lines). The PR description still says the email was hyperlinked, but the notebook text uses plain email addresses.
3. questions: one inline question on whether the `jupyter-book<2` pin should remain in this PR as a short-term compatibility fix now that issue #13 tracks the v2 migration.
4. tests run and outcomes: `uv pip install --python .venv/bin/python -r requirements.txt` passed; changed notebook JSON validation passed; `git diff --check origin/main...HEAD` passed; stale old-fork/email placeholder search had no matches; `.venv/bin/jupyter-book build .` passed and generated `_build/html` cleanly with Jupyter Book 1.0.4.post1; generated `_build/` was removed after the build. GitHub reports no checks for this branch.
5. merge as-is: I would use COMMENT rather than APPROVE until the nonblocking notebook text/PR-description cleanup and the build-tooling direction question are handled or explicitly accepted.

2026-05-10 22:55 UTC, bernalde commented on requirements.txt
> +jupyter-book<2
Question: This pins the repo to the classic Jupyter Book line so the existing `jupyter-book build .` workflow works again. Since #13 now tracks migrating this repo to the Jupyter Book v2 workflow used in QuIP, should this PR keep the v1 pin as an intentional short-term compatibility fix, or should the build-tooling change be split/reverted here and left entirely to the migration issue?

2026-05-10 23:05 UTC, bernalde commented
Pushed commit 0ff3ee0 (`Polish notebook attribution text`).

Main changes made:
- Corrected the notebook attribution text in the three changed source notebooks: `Development`, `GitHub`, and single spacing after the semicolon.
- Converted the author email text in those notebook attribution lines to explicit `mailto:` links, including Zedong Peng's Purdue address.
- Applied the same GitHub capitalization cleanup to the user-facing issue-link text in `intro.md`.

Tests run and results:
- `uv pip install --python .venv/bin/python -r requirements.txt`: passed.
- Targeted JSON validation of the three changed notebooks with `.venv/bin/python`: passed.
- Reviewed-string search for `Developement`, `;  the content`, old fork URL, old Zedong placeholder, `123.com`, and ` at purdue.edu`: no matches in the changed source files.
- Presence check for `mailto:`, `GitHub`, and `Development Team`: passed in the three notebook attribution lines.
- `git diff --check`: passed.
- `.venv/bin/jupyter-book build .`: passed and generated `_build/html` cleanly; generated `_build/` was removed before commit.

Comments intentionally not addressed:
- The `jupyter-book<2` inline question was addressed without a code change: keeping the v1 pin in this PR as a short-term compatibility fix so the existing documented CI command works, while the v2 migration is tracked separately in #13.
- The older discussion saying the branch could be closed was not acted on by closing the PR because the current request was to address review feedback on this open branch.

Remaining risks or follow-up items:
- Jupyter Book v2 migration remains follow-up work in #13.
- GitHub currently reports no checks for this branch, so local validation is the available evidence for this pass.

2026-05-10 23:05 UTC, bernalde commented on notebooks/python/python-exercises.ipynb
> +    "This notebook contains material from the Pyomo Summer Workshop 2018 by the Pyomo Developement Team and the notebook is developed by David Bernal (dbernaln@purdue.edu), Zedong Peng (peng372@purdu
Addressed in https://github.com/SECQUOIA/pyomo-summer-ws/commit/0ff3ee0. Converted the author email text to explicit `mailto:` links, including Zedong Peng at `peng372@purdue.edu`, so the notebook text now matches the PR description.

2026-05-10 23:05 UTC, bernalde commented on notebooks/python/python-exercises.ipynb
> +    "This notebook contains material from the Pyomo Summer Workshop 2018 by the Pyomo Developement Team and the notebook is developed by David Bernal (dbernaln@purdue.edu), Zedong Peng (peng372@purdu
Addressed in https://github.com/SECQUOIA/pyomo-summer-ws/commit/0ff3ee0. Corrected `Development`, `GitHub`, and the semicolon spacing in this notebook intro line; the same cleanup was applied to the other changed notebook intro lines.

2026-05-10 23:05 UTC, bernalde commented on notebooks/PyomoNonlinear/PyomoNonlinear.ipynb
> +    "This notebook contains material from the Pyomo Summer Workshop 2018 by the Pyomo Developement Team and the notebook is developed by David Bernal (dbernaln@purdue.edu), Zedong Peng (peng372@purdu
Addressed in https://github.com/SECQUOIA/pyomo-summer-ws/commit/0ff3ee0. Corrected `Development`, `GitHub`, and the semicolon spacing in this notebook intro line.

2026-05-10 23:05 UTC, bernalde commented on notebooks/PyomoFundamentals/Fundamentals.ipynb
> +    "This notebook contains material from the Pyomo Summer Workshop 2018 by the Pyomo Developement Team and the notebook is developed by David Bernal (dbernaln@purdue.edu), Zedong Peng (peng372@purdu
Addressed in https://github.com/SECQUOIA/pyomo-summer-ws/commit/0ff3ee0. Corrected `Development`, `GitHub`, and the semicolon spacing in this notebook intro line.

2026-05-10 23:05 UTC, bernalde commented on requirements.txt
> +jupyter-book<2
Addressed without another code change. Keeping `jupyter-book<2` from https://github.com/SECQUOIA/pyomo-summer-ws/commit/389f894 as a short-term compatibility fix for the existing `jupyter-book build .` workflow; the v2 migration is tracked separately in https://github.com/SECQUOIA/pyomo-summer-ws/issues/13.

2026-05-10 23:08 UTC, merged